### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mbbcat** [vbuell/torram#13]
torram.py", line 75 print fmt.format(pattern.format(num_of_success, len(mixed_pieces), len(file_infos)), 'RED', 'BOLD') ^ SyntaxError: invalid syntax

**Comment by mbbcat** [comment]
any ideas please?

**Comment by vbuell** [comment]
What version of python do you use? I guess it was written for python 2 and never ported to python 3 syntax since then. Let me see if all dependencies were updated to support py3 and I'll port to python3.

Thanks for the report!

**Comment by vbuell** [comment]
The project was ported to python3. Please try the latest master.

Closing the issue. If you face any other issues please create another bug report.
